### ISSUE TITLE
[SERVER] fix CORS

### ISSUE THREAD

**Issue by ultimatemonty** [frolfr/frolfr-server#194]
Trying to reset my password and getting a CORS error from the API. Boo CORS. Hooray Coors!

![image](https://cloud.githubusercontent.com/assets/7738688/17388241/dafc92c2-59c8-11e6-9a3d-a3e90beb1a22.png)

**Comment by gschorkopf** [comment]
Is this an issue with the server or client?

**Comment by ultimatemonty** [comment]
@gschorkopf unsure but it looks like API? The error is complaining about a lack of a CORS header on the password reset page. I don't know much about Rails but a quick glance at the controller looked OK - it extends application_controller which is definitely adding the CORS headers.

**Comment by gschorkopf** [comment]
I believe this issue has been resolved. Mind checking it out for yourself? frolfr.com/password/reset

**Comment by ultimatemonty** [comment]
@gschorkopf still seeing the issue. On phone so can't see network request

**Comment by gschorkopf** [comment]
Darn! It's working for me. The issue is with gmail, not with CORS.

<img width="620" alt="screen shot 2016-08-18 at 6 40 20 pm" src="https://cloud.githubusercontent.com/assets/2623668/17793154/48add99c-6573-11e6-9bed-14e5df992184.png">

Lemme know when you have more information!

**Comment by ultimatemonty** [comment]
looks like it is specific to my `chris.mcculler@gmail.com` account. tried with `ultimatemonty@gmail.com` and it worked. It's giving a CORS error message but the error code is a HTTP 500:

![image](https://cloud.githubusercontent.com/assets/7738688/17793252/d15a3772-6573-11e6-9043-4634456b069c.png)

![image](https://cloud.githubusercontent.com/assets/7738688/17793282/09d284f6-6574-11e6-9038-b9cfa91ec77b.png)

**Comment by gschorkopf** [comment]
Alright, so it would *appear* the bug has been fixed, but it opens up a different issue that I'll address.

ultimatemonty@gmail.com working = 🐛 solved.
chris.mcculler@gmail.com not working makes sense, because I merged that account with ultimatemonty and so the chris.mcculler@gmail.com account no longer exists!

**Comment by gschorkopf** [comment]
The new issue: it should really return a 404 or something, not a 500. But as long as there's an error message on the frontend, I guess it's not a huge deal right now.

**Comment by ultimatemonty** [comment]
got it thanks!

**Comment by gschorkopf** [comment]
Given that it appears to work for multiple accounts (your active ultimatemonty one and my gschorkopf one), I'll close this. Thanks again for opening these issues! It's been fun to work on.

**Comment by ultimatemonty** [comment]
@gschorkopf next goal: rewrite the API in Phoenix (for the learns!)
